version: '3.1'

services:
  mongo:
    image: mongo:3.6.23
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - configdb:/data/configdb
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: s3cret
      ME_CONFIG_MONGODB_URL: mongodb://root:s3cret@mongo:27017/

volumes:
  configdb:
  db:
