try:
    ...
    Codeblock der SampleError und AnotherSampleError werfen kann
    ...
except SampleError as err:
    ...
    Exception-Handling
    ...
except AnotherSampleError as err:
    ...
    Exception-Handling
    ...
finally
    ...
    Codeblock. Immer ausgeführt. Schließen von Resourcen, etc.
    ...    
